USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM 'file:///clientes.csv' AS line FIELDTERMINATOR '|'
MATCH (c:Cliente { id_cte:toInteger(line.ID_CTE)})
SET c.ESTATUS_MIGRACION = toInteger(line.ESTATUS_MIGRACION),
    c.DESC_ESTATUS_MIGRACION = line.ESTATUS_MIGRACION,
	c.NIVEL_EDUC = line.NIVEL_EDUC;