

CREATE TABLE  ANALITICAAFORE.ADMIN.CENIC_MRF2MERGE_TRANS_DEMO AS (



WITH Demogra AS (
 SELECT *
  FROM ANALITICAAFORE.ADMIN.BASECLIENTES_SISTEMA_REC 
 ), 
 
 /*
  VilmaTel AS (
 SELECT  NUMEROCLIENTE 
       , TIPOTELEFONO
       , NUMEROTELEFONOORIGEN
       , NUMEROTELEFONO
       , CARRIER, ROW_NUMBER() OVER( PARTITION BY NUMEROCLIENTE  ORDER BY  NUMEROCLIENTE) AS INDICE 

  FROM CENIC.BIG.MAETELEFONOS_MAY19
 ), 
   temp1 AS (
 SELECT IDU_CLIENTECODIGOMAESTRO, 
         DES_CORREOELECTRONICO
       , DES_ORIGEN
  FROM CENIC.BIG.MAETELEFONOS_MAY20
   where DES_ESTATUS ='Válido' ), 
   
   VilmaEmail as ( 
   SELECT IDU_CLIENTECODIGOMAESTRO, 
         DES_CORREOELECTRONICO
       , DES_ORIGEN, ROW_NUMBER() OVER ( PARTITION BY IDU_CLIENTECODIGOMAESTRO ORDER BY IDU_CLIENTECODIGOMAESTRO  ) AS INDICE
  FROM temp1 
   ), */
   
  res as (
 SELECT distinct   t.FECHA_TICKET
       , t.ID_TIENDA
       , t.ID_TICKET
       , t.PROD_SKU
       , t.PROD_DEP
       , t.DESC_PROD_DEP
       , t.PROD_CLAS
       , t.DESC_PROD_CLAS
       , t.PROD_FAM
       , t.DESC_PROD_FAM
       , t.PROD_AREA
       , t.PROD_CATEGORIA
       , t.DESC_PROD_CATEGORIA
       , t.IMPORTE_VTA
       , t.CANTIDAD_VTA
       , t.PROD_PRECIO_PROMEDIO
       , t.TIPOCOMPRA, 
 Demogra.*/*, 
        tel.TIPOTELEFONO
       , tel.NUMEROTELEFONOORIGEN
       , tel.NUMEROTELEFONO
       , tel.CARRIER
	   , Email.DES_CORREOELECTRONICO
	   , Email.DES_ORIGEN */
	   FROM ANALITICAAFORE.ADMIN.TRANSACCIONES_SISTEMA_REC as t 
	LEFT JOIN  Demogra 
	on t.ID_CTE =Demogra.ID_CTE
	/*LEFT JOIN  ( select  distinct NUMEROCLIENTE,  TIPOTELEFONO,NUMEROTELEFONOORIGEN, NUMEROTELEFONO, CARRIER   
	              from VilmaTel WHERE  INDICE = 1) tel 
	ON Demogra.ID_CTE = tel.NUMEROCLIENTE
	LEFT JOIN (select  distinct  IDU_CLIENTECODIGOMAESTRO, DES_CORREOELECTRONICO,DES_ORIGEN
	           from   VilmaEmail WHERE INDICE = 1) as Email
	ON Demogra.ID_CTE =Email.IDU_CLIENTECODIGOMAESTRO */
	)
	
	select * from res ) DISTRIBUTE ON  (ID_CTE) 
